apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: python-addy
        image: barrycontainerregistry.azurecr.io/python-addy:v1.4.0
        volumeMounts:
          - name: hello-world-configmap-volume
            mountPath: /etc/config
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
          - name: web
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 25
      volumes:
        - name: hello-world-configmap-volume
          configMap:
            name: hello-world-configmap