---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
  namespace: example
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: hello-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-agic-ig
  namespace: example
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-svc
            port:
              number: 80